export const DB = {
  users: [
    {
      id: 1,
      name: "Super Admin",
      username: "admin",
      password: "admin123",
      role: "admin",
      avatar: "SA",
    },
  ],
  roles: [
    { id: "admin", label: "Admin", color: "#ef4444" },
    { id: "pinca", label: "Pinca", color: "#f59e0b" },
    { id: "cabang", label: "Cabang", color: "#3b82f6" },
    { id: "mikro", label: "Mikro", color: "#10b981" },
    { id: "publik", label: "Publik", color: "#10b981" },
  ],
  menus: [
    {
      id: 1,
      title: "📊 RM SME",
      icon: "📊",
      description: "Akses laporan & data keuangan",
      type: "folder",
      order: 2,
      color: "#f59e0b",
      roles: ["admin", "pinca"],
      submenus: [],
    },
    {
      id: 2,
      title: "MIKRO",
      icon: "📋",
      description: "Data kegiatan & operasional",
      type: "folder",
      order: 3,
      color: "#3b82f6",
      roles: ["admin"],
      submenus: [],
    },
    {
      id: 4,
      title: "DAILY",
      icon: "🌐",
      description: "Daily Dashboard Briboy",
      type: "link",
      order: 1,
      color: "#23614d",
      url: "https://www.example.com",
      roles: ["admin", "pinca"],
      submenus: [],
    },
  ],
  profile: {
    name: "Portal Layanan",
    subtitle: "Akses mudah ke semua dokumen & data",
    logo: "🏢",
    bgGradient: "from-sky-50 via-white to-indigo-50",
  },
};
